# Writes audiodsp_revision.h: which audiodsp a firmware was built from.
#
#   cmake -DMOD_DIR=<this repository> -DOUT=<header> -P audiodsp_revision.cmake
#
# micropython.cmake runs this on every build. The header is rewritten only when
# its contents change, so an unchanged checkout recompiles nothing. The strings
# are those micropython.mk computes; see the comment there.

execute_process(
    COMMAND git -C ${MOD_DIR} describe --tags --match v[0-9]* --always --dirty --abbrev=7
    OUTPUT_VARIABLE REVISION
    OUTPUT_STRIP_TRAILING_WHITESPACE
    RESULT_VARIABLE RESULT
    ERROR_QUIET)
if(NOT RESULT EQUAL 0 OR NOT REVISION)
    set(REVISION "unknown")
endif()

if(EXISTS ${MOD_DIR}/VERSION)
    file(READ ${MOD_DIR}/VERSION VERSION)
    string(STRIP "${VERSION}" VERSION)
else()
    set(VERSION "0.0.0+unknown")
endif()

set(CONTENT "// Generated by audiodsp_revision.cmake. Do not edit.\n#define AUDIODSP_VERSION \"${VERSION}\"\n#define AUDIODSP_REVISION \"${REVISION}\"\n")
set(OLD "")
if(EXISTS ${OUT})
    file(READ ${OUT} OLD)
endif()
if(NOT OLD STREQUAL CONTENT)
    file(WRITE ${OUT} "${CONTENT}")
endif()
